{"nodes":[{"pos":[12,61],"content":"Compiler Warning (level 4) C4571 | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Compiler Warning (level 4) C4571 | Microsoft Docs","pos":[0,49]}]},{"pos":[610,642],"content":"Compiler Warning (level 4) C4571","linkify":"Compiler Warning (level 4) C4571","nodes":[{"content":"Compiler Warning (level 4) C4571","pos":[0,32]}]},{"content":"Informational: catch(...) semantics changed since Visual C++ 7.1; structured exceptions (SEH) are no longer caught","pos":[643,757]},{"pos":[764,839],"content":"C4571 is generated for every catch(...) block when compiling with <bpt id=\"p1\">**</bpt>/EHs<ept id=\"p1\">**</ept>.","source":"C4571 is generated for every catch(...) block when compiling with **/EHs**."},{"content":"When compiling with <bpt id=\"p1\">**</bpt>/EHs<ept id=\"p1\">**</ept>, a catch(...) block will not catch a structured exception (divide by zero, null pointer, for example); a catch(...) block will only catch explicitly-thrown, C++ exceptions.","pos":[846,1047],"source":"When compiling with **/EHs**, a catch(...) block will not catch a structured exception (divide by zero, null pointer, for example); a catch(...) block will only catch explicitly-thrown, C++ exceptions."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../cpp/exception-handling-in-visual-cpp.md)</ept>.","pos":[1049,1143],"source":"  For more information, see [Exception Handling](../../cpp/exception-handling-in-visual-cpp.md)."},{"content":"This warning is off by default.","pos":[1150,1181]},{"content":"Turn this warning on to ensure that when you compile with <bpt id=\"p1\">**</bpt>/EHs<ept id=\"p1\">**</ept> your catch (...) blocks do not intend to catch structured exceptions.","pos":[1183,1319],"source":"  Turn this warning on to ensure that when you compile with **/EHs** your catch (...) blocks do not intend to catch structured exceptions."},{"content":"See <bpt id=\"p1\">[</bpt>Compiler Warnings That Are Off by Default<ept id=\"p1\">](../../preprocessor/compiler-warnings-that-are-off-by-default.md)</ept> for more information.","pos":[1321,1455],"source":"  See [Compiler Warnings That Are Off by Default](../../preprocessor/compiler-warnings-that-are-off-by-default.md) for more information."},{"content":"You can resolve C4571 in one of the following ways,","pos":[1462,1513]},{"pos":[1523,1617],"content":"Compile with <bpt id=\"p1\">**</bpt>/EHa<ept id=\"p1\">**</ept> if you still want your catch(...) blocks to catch structured exceptions.","source":"Compile with **/EHa** if you still want your catch(...) blocks to catch structured exceptions."},{"content":"Do not enable C4571 if you do not want your catch(...) blocks to catch structured exceptions, but you still want to use catch(...) blocks.","pos":[1627,1765]},{"content":"You can still catch structured exceptions using the structured exception handling keywords (<bpt id=\"p1\">**</bpt>__try<ept id=\"p1\">**</ept>, <bpt id=\"p2\">**</bpt>__except<ept id=\"p2\">**</ept>, and <bpt id=\"p3\">**</bpt>__finally<ept id=\"p3\">**</ept>).","pos":[1767,1903],"source":"  You can still catch structured exceptions using the structured exception handling keywords (**__try**, **__except**, and **__finally**)."},{"content":"But remember, when compiled <bpt id=\"p1\">**</bpt>/EHs<ept id=\"p1\">**</ept> destructors will only be called when a C++ exception is thrown, not when an SEH exception occurs.","pos":[1905,2039],"source":"  But remember, when compiled **/EHs** destructors will only be called when a C++ exception is thrown, not when an SEH exception occurs."},{"content":"Replace catch(...) block with catch blocks for specific C++ exceptions, and optionally, add structured exception handling around the C++ exception handling (<bpt id=\"p1\">**</bpt>__try<ept id=\"p1\">**</ept>, <bpt id=\"p2\">**</bpt>__except<ept id=\"p2\">**</ept>, and <bpt id=\"p3\">**</bpt>__finally<ept id=\"p3\">**</ept>).","pos":[2049,2250],"source":"Replace catch(...) block with catch blocks for specific C++ exceptions, and optionally, add structured exception handling around the C++ exception handling (**__try**, **__except**, and **__finally**)."},{"content":"See <bpt id=\"p1\">[</bpt>Structured Exception Handling (C/C++)<ept id=\"p1\">](../../cpp/structured-exception-handling-c-cpp.md)</ept> for more information.","pos":[2252,2367],"source":"  See [Structured Exception Handling (C/C++)](../../cpp/structured-exception-handling-c-cpp.md) for more information."},{"pos":[2374,2486],"content":"See <bpt id=\"p1\">[</bpt>/EH (Exception Handling Model)<ept id=\"p1\">](../../build/reference/eh-exception-handling-model.md)</ept> for more information.","source":"See [/EH (Exception Handling Model)](../../build/reference/eh-exception-handling-model.md) for more information."},{"pos":[2495,2502],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following sample generates C4571.","pos":[2506,2543]}],"content":"---\ntitle: \"Compiler Warning (level 4) C4571 | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"error-reference\"\nf1_keywords: \n  - \"C4571\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"C4571\"\nms.assetid: 07aa17bd-b15c-4266-824c-57cc445e8edd\ncaps.latest.revision: 12\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Compiler Warning (level 4) C4571\nInformational: catch(...) semantics changed since Visual C++ 7.1; structured exceptions (SEH) are no longer caught  \n  \n C4571 is generated for every catch(...) block when compiling with **/EHs**.  \n  \n When compiling with **/EHs**, a catch(...) block will not catch a structured exception (divide by zero, null pointer, for example); a catch(...) block will only catch explicitly-thrown, C++ exceptions.  For more information, see [Exception Handling](../../cpp/exception-handling-in-visual-cpp.md).  \n  \n This warning is off by default.  Turn this warning on to ensure that when you compile with **/EHs** your catch (...) blocks do not intend to catch structured exceptions.  See [Compiler Warnings That Are Off by Default](../../preprocessor/compiler-warnings-that-are-off-by-default.md) for more information.  \n  \n You can resolve C4571 in one of the following ways,  \n  \n-   Compile with **/EHa** if you still want your catch(...) blocks to catch structured exceptions.  \n  \n-   Do not enable C4571 if you do not want your catch(...) blocks to catch structured exceptions, but you still want to use catch(...) blocks.  You can still catch structured exceptions using the structured exception handling keywords (**__try**, **__except**, and **__finally**).  But remember, when compiled **/EHs** destructors will only be called when a C++ exception is thrown, not when an SEH exception occurs.  \n  \n-   Replace catch(...) block with catch blocks for specific C++ exceptions, and optionally, add structured exception handling around the C++ exception handling (**__try**, **__except**, and **__finally**).  See [Structured Exception Handling (C/C++)](../../cpp/structured-exception-handling-c-cpp.md) for more information.  \n  \n See [/EH (Exception Handling Model)](../../build/reference/eh-exception-handling-model.md) for more information.  \n  \n## Example  \n The following sample generates C4571.  \n  \n```  \n// C4571.cpp  \n// compile with: /EHs /W4 /c  \n#pragma warning(default : 4571)  \nint main() {  \n   try {  \n      int i = 0, j = 1;  \n      j /= i;   // this will throw a SE (divide by zero)  \n   }  \n   catch(...) {}   // C4571 warning  \n}  \n```"}