{"nodes":[{"pos":[12,49],"content":"__uncaught_exception | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"__uncaught_exception | Microsoft Docs","pos":[0,37]}]},{"content":"__uncaught_exception","pos":[927,947]},{"pos":[948,1148],"content":"Indicates whether one or more exceptions have been thrown, but have not yet been handled by the corresponding <ph id=\"ph1\">`catch`</ph> block of a <bpt id=\"p1\">[</bpt>try-catch<ept id=\"p1\">](../../cpp/try-throw-and-catch-statements-cpp.md)</ept> statement.","source":"Indicates whether one or more exceptions have been thrown, but have not yet been handled by the corresponding `catch` block of a [try-catch](../../cpp/try-throw-and-catch-statements-cpp.md) statement."},{"content":"Syntax","pos":[1157,1163]},{"content":"Return Value","pos":[1227,1239]},{"pos":[1250,1372],"content":"from the time an exception is thrown in a <ph id=\"ph1\">`try`</ph> block until the matching <ph id=\"ph2\">`catch`</ph> block is initialized; otherwise, <ph id=\"ph3\">`false`</ph>.","source":" from the time an exception is thrown in a `try` block until the matching `catch` block is initialized; otherwise, `false`."},{"content":"Remarks","pos":[1381,1388]},{"content":"Requirements","pos":[1397,1409]},{"content":"Routine","pos":[1416,1423]},{"content":"Required header","pos":[1424,1439]},{"content":"__uncaught_exception","pos":[1484,1504]},{"content":"eh.h","pos":[1505,1509]},{"content":"See Also","pos":[1519,1527]},{"content":"try, throw, and catch Statements (C++)","pos":[1532,1570]}],"content":"---\ntitle: \"__uncaught_exception | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\napiname: \n  - \"__uncaught_exception\"\napilocation: \n  - \"msvcrt.dll\"\n  - \"msvcr80.dll\"\n  - \"msvcr90.dll\"\n  - \"msvcr100.dll\"\n  - \"msvcr100_clr0400.dll\"\n  - \"msvcr110.dll\"\n  - \"msvcr110_clr0400.dll\"\n  - \"msvcr120.dll\"\n  - \"msvcr120_clr0400.dll\"\n  - \"ucrtbase.dll\"\napitype: \"DLLExport\"\nf1_keywords: \n  - \"__uncaught_exception\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"__uncaught_exception\"\nms.assetid: 4d9b75c6-c9c7-4876-b761-ea9ab1925e96\ncaps.latest.revision: 2\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# __uncaught_exception\nIndicates whether one or more exceptions have been thrown, but have not yet been handled by the corresponding `catch` block of a [try-catch](../../cpp/try-throw-and-catch-statements-cpp.md) statement.  \n  \n## Syntax  \n  \n```cpp  \nbool __uncaught_exception(  \n   );  \n```  \n  \n## Return Value  \n `true` from the time an exception is thrown in a `try` block until the matching `catch` block is initialized; otherwise, `false`.  \n  \n## Remarks  \n  \n## Requirements  \n  \n|Routine|Required header|  \n|-------------|---------------------|  \n|__uncaught_exception|eh.h|  \n  \n## See Also  \n [try, throw, and catch Statements (C++)](../../cpp/try-throw-and-catch-statements-cpp.md)"}