{"nodes":[{"pos":[12,51],"content":"CMemoryException Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"CMemoryException Class | Microsoft Docs","pos":[0,39]}]},{"pos":[746,768],"content":"CMemoryException Class","linkify":"CMemoryException Class","nodes":[{"content":"CMemoryException Class","pos":[0,22]}]},{"content":"Represents an out-of-memory exception condition.","pos":[769,817]},{"pos":[826,832],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[907,914],"content":"Members","linkify":"Members","nodes":[{"content":"Members","pos":[0,7]}]},{"pos":[924,943],"content":"Public Constructors","linkify":"Public Constructors","nodes":[{"content":"Public Constructors","pos":[0,19]}]},{"content":"Name","pos":[950,954]},{"content":"Description","pos":[955,966]},{"pos":[1004,1077],"content":"<bpt id=\"p1\">[</bpt>CMemoryException::CMemoryException<ept id=\"p1\">](#cmemoryexception__cmemoryexception)</ept>","source":"[CMemoryException::CMemoryException](#cmemoryexception__cmemoryexception)"},{"pos":[1078,1117],"content":"Constructs a <ph id=\"ph1\">`CMemoryException`</ph> object.","source":"Constructs a `CMemoryException` object."},{"pos":[1127,1134],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"No further qualification is necessary or possible.","pos":[1138,1188]},{"content":"Memory exceptions are thrown automatically by <bpt id=\"p1\">**</bpt>new<ept id=\"p1\">**</ept>.","pos":[1189,1243],"source":" Memory exceptions are thrown automatically by **new**."},{"content":"If you write your own memory functions, using <ph id=\"ph1\">`malloc`</ph>, for example, then you are responsible for throwing memory exceptions.","pos":[1244,1369],"source":" If you write your own memory functions, using `malloc`, for example, then you are responsible for throwing memory exceptions."},{"pos":[1376,1503],"content":"For more information on <ph id=\"ph1\">`CMemoryException`</ph>, see the article <bpt id=\"p1\">[</bpt>Exception Handling (MFC)<ept id=\"p1\">](../../mfc/exception-handling-in-mfc.md)</ept>.","source":"For more information on `CMemoryException`, see the article [Exception Handling (MFC)](../../mfc/exception-handling-in-mfc.md)."},{"pos":[1512,1533],"content":"Inheritance Hierarchy","linkify":"Inheritance Hierarchy","nodes":[{"content":"Inheritance Hierarchy","pos":[0,21]}]},{"pos":[1537,1584],"content":"<bpt id=\"p1\">[</bpt>CObject<ept id=\"p1\">](../../mfc/reference/cobject-class.md)</ept>","source":"[CObject](../../mfc/reference/cobject-class.md)"},{"pos":[1591,1644],"content":"<bpt id=\"p1\">[</bpt>CException<ept id=\"p1\">](../../mfc/reference/cexception-class.md)</ept>","source":"[CException](../../mfc/reference/cexception-class.md)"},{"pos":[1651,1716],"content":"<bpt id=\"p1\">[</bpt>CSimpleException<ept id=\"p1\">](../../mfc/reference/csimpleexception-class.md)</ept>","source":"[CSimpleException](../../mfc/reference/csimpleexception-class.md)"},{"pos":[1750,1762],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1766,1783],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> afx.h","source":"**Header:** afx.h"},{"pos":[1793,1878],"content":"<bpt id=\"p1\">&lt;a name=\"cmemoryexception__cmemoryexception\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CMemoryException::CMemoryException","linkify":"<a name=\"cmemoryexception__cmemoryexception\"></a>  CMemoryException::CMemoryException","source":"<a name=\"cmemoryexception__cmemoryexception\"></a>  CMemoryException::CMemoryException"},{"pos":[1882,1921],"content":"Constructs a <ph id=\"ph1\">`CMemoryException`</ph> object.","source":"Constructs a `CMemoryException` object."},{"pos":[1968,1975],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"Do not use this constructor directly, but rather call the global function <bpt id=\"p1\">[</bpt>AfxThrowMemoryException<ept id=\"p1\">](exception-processing.md#afxthrowmemoryexception)</ept>.","pos":[1979,2128],"source":"Do not use this constructor directly, but rather call the global function [AfxThrowMemoryException](exception-processing.md#afxthrowmemoryexception)."},{"content":"this global function can succeed in an out-of-memory situation because it constructs the exception object in previously allocated memory.","pos":[2129,2266]},{"content":"for more information about exception processing, see the article <bpt id=\"p1\">[</bpt>exceptions<ept id=\"p1\">](../exception-handling-in-mfc.md)</ept>.","pos":[2267,2378],"source":" for more information about exception processing, see the article [exceptions](../exception-handling-in-mfc.md)."},{"pos":[2387,2395],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>CException Class<ept id=\"p1\">](cexception-class.md)</ept><ph id=\"ph1\"> </ph>","pos":[2399,2439],"source":"[CException Class](cexception-class.md) "},{"content":"<bpt id=\"p1\"> [</bpt>Hierarchy Chart<ept id=\"p1\">](../hierarchy-chart.md)</ept>","pos":[2442,2483],"source":" [Hierarchy Chart](../hierarchy-chart.md)"}],"content":"---\ntitle: \"CMemoryException Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"reference\"\nf1_keywords: \n  - \"CMemoryException\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"CMemoryException class\"\n  - \"memory exceptions\"\n  - \"exceptions, memory type\"\n  - \"C++ exception handling, memory\"\n  - \"memory, exception handling\"\nms.assetid: 9af0ed57-d12a-45ca-82b5-c910a60f7edf\ncaps.latest.revision: 20\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# CMemoryException Class\nRepresents an out-of-memory exception condition.  \n  \n## Syntax  \n  \n```  \nclass CMemoryException : public CSimpleException  \n```  \n  \n## Members  \n  \n### Public Constructors  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CMemoryException::CMemoryException](#cmemoryexception__cmemoryexception)|Constructs a `CMemoryException` object.|  \n  \n## Remarks  \n No further qualification is necessary or possible. Memory exceptions are thrown automatically by **new**. If you write your own memory functions, using `malloc`, for example, then you are responsible for throwing memory exceptions.  \n  \n For more information on `CMemoryException`, see the article [Exception Handling (MFC)](../../mfc/exception-handling-in-mfc.md).  \n  \n## Inheritance Hierarchy  \n [CObject](../../mfc/reference/cobject-class.md)  \n  \n [CException](../../mfc/reference/cexception-class.md)  \n  \n [CSimpleException](../../mfc/reference/csimpleexception-class.md)  \n  \n `CMemoryException`  \n  \n## Requirements  \n **Header:** afx.h  \n  \n##  <a name=\"cmemoryexception__cmemoryexception\"></a>  CMemoryException::CMemoryException  \n Constructs a `CMemoryException` object.  \n  \n```  \nCMemoryException();  \n```  \n  \n### Remarks  \n Do not use this constructor directly, but rather call the global function [AfxThrowMemoryException](exception-processing.md#afxthrowmemoryexception). this global function can succeed in an out-of-memory situation because it constructs the exception object in previously allocated memory. for more information about exception processing, see the article [exceptions](../exception-handling-in-mfc.md).  \n  \n## See Also  \n [CException Class](cexception-class.md)   \n [Hierarchy Chart](../hierarchy-chart.md)\n\n\n\n"}