{"nodes":[{"pos":[12,70],"content":"scheduler_resource_allocation_error Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"scheduler_resource_allocation_error Class | Microsoft Docs","pos":[0,58]}]},{"pos":[697,738],"content":"scheduler_resource_allocation_error Class","linkify":"scheduler_resource_allocation_error Class","nodes":[{"content":"scheduler_resource_allocation_error Class","pos":[0,41]}]},{"content":"This class describes an exception thrown because of a failure to acquire a critical resource in the Concurrency Runtime.","pos":[739,859]},{"pos":[868,874],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[963,970],"content":"Members","linkify":"Members","nodes":[{"content":"Members","pos":[0,7]}]},{"pos":[980,999],"content":"Public Constructors","linkify":"Public Constructors","nodes":[{"content":"Public Constructors","pos":[0,19]}]},{"content":"Name","pos":[1006,1010]},{"content":"Description","pos":[1011,1022]},{"pos":[1060,1153],"content":"<bpt id=\"p1\">[</bpt>scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor<ept id=\"p1\">](#ctor)</ept>","source":"[scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor](#ctor)"},{"content":"Overloaded.","pos":[1154,1165]},{"content":"Constructs a <ph id=\"ph1\">`scheduler_resource_allocation_error`</ph> object.","pos":[1166,1224],"source":" Constructs a `scheduler_resource_allocation_error` object."},{"pos":[1235,1249],"content":"Public Methods","linkify":"Public Methods","nodes":[{"content":"Public Methods","pos":[0,14]}]},{"content":"Name","pos":[1256,1260]},{"content":"Description","pos":[1261,1272]},{"pos":[1310,1387],"content":"<bpt id=\"p1\">[</bpt>scheduler_resource_allocation_error::get_error_code Method<ept id=\"p1\">](#get_error_code)</ept>","source":"[scheduler_resource_allocation_error::get_error_code Method](#get_error_code)"},{"content":"Returns the error code that caused the exception.","pos":[1388,1437]},{"pos":[1447,1454],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This exception is typically thrown when a call to the operating system from within the Concurrency Runtime fails.","pos":[1458,1571]},{"content":"The error code which would normally be returned from a call to the Win32 method <ph id=\"ph1\">`GetLastError`</ph> is converted to a value of type <ph id=\"ph2\">`HRESULT`</ph> and can be retrieved using the <ph id=\"ph3\">`get_error_code`</ph> method.","pos":[1572,1764],"source":" The error code which would normally be returned from a call to the Win32 method `GetLastError` is converted to a value of type `HRESULT` and can be retrieved using the `get_error_code` method."},{"pos":[1773,1794],"content":"Inheritance Hierarchy","linkify":"Inheritance Hierarchy","nodes":[{"content":"Inheritance Hierarchy","pos":[0,21]}]},{"pos":[1862,1874],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1878,1898],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> concrt.h","source":"**Header:** concrt.h"},{"pos":[1905,1931],"content":"<bpt id=\"p1\">**</bpt>Namespace:<ept id=\"p1\">**</ept> concurrency","source":"**Namespace:** concurrency"},{"pos":[1941,2030],"content":"<bpt id=\"p1\">&lt;a name=\"get_error_code\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  scheduler_resource_allocation_error::get_error_code Method","linkify":"<a name=\"get_error_code\"></a>  scheduler_resource_allocation_error::get_error_code Method","source":"<a name=\"get_error_code\"></a>  scheduler_resource_allocation_error::get_error_code Method"},{"content":"Returns the error code that caused the exception.","pos":[2034,2083]},{"pos":[2146,2158],"content":"Return Value","linkify":"Return Value","nodes":[{"content":"Return Value","pos":[0,12]}]},{"pos":[2162,2221],"content":"The <ph id=\"ph1\">`HRESULT`</ph> value of the error that caused the exception.","source":"The `HRESULT` value of the error that caused the exception."},{"pos":[2231,2336],"content":"<bpt id=\"p1\">&lt;a name=\"ctor\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor","linkify":"<a name=\"ctor\"></a>  scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor","source":"<a name=\"ctor\"></a>  scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor"},{"pos":[2340,2398],"content":"Constructs a <ph id=\"ph1\">`scheduler_resource_allocation_error`</ph> object.","source":"Constructs a `scheduler_resource_allocation_error` object."},{"pos":[2608,2618],"content":"Parameters","linkify":"Parameters","nodes":[{"content":"Parameters","pos":[0,10]}]},{"content":"A descriptive message of the error.","pos":[2636,2671]},{"content":"The <ph id=\"ph1\">`HRESULT`</ph> value of the error that caused the exception.","pos":[2692,2751],"source":" The `HRESULT` value of the error that caused the exception."},{"pos":[2760,2768],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"pos":[2772,2821],"content":"<bpt id=\"p1\">[</bpt>concurrency Namespace<ept id=\"p1\">](concurrency-namespace.md)</ept>","source":"[concurrency Namespace](concurrency-namespace.md)"}],"content":"---\ntitle: \"scheduler_resource_allocation_error Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nf1_keywords: \n  - \"concrt/concurrency::scheduler_resource_allocation_error\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"scheduler_resource_allocation_error class\"\nms.assetid: 8b40449a-7abb-4d0a-bb85-c0e9a495ae97\ncaps.latest.revision: 19\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# scheduler_resource_allocation_error Class\nThis class describes an exception thrown because of a failure to acquire a critical resource in the Concurrency Runtime.  \n  \n## Syntax  \n  \n```\nclass scheduler_resource_allocation_error : public std::exception;\n```  \n  \n## Members  \n  \n### Public Constructors  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor](#ctor)|Overloaded. Constructs a `scheduler_resource_allocation_error` object.|  \n  \n### Public Methods  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[scheduler_resource_allocation_error::get_error_code Method](#get_error_code)|Returns the error code that caused the exception.|  \n  \n## Remarks  \n This exception is typically thrown when a call to the operating system from within the Concurrency Runtime fails. The error code which would normally be returned from a call to the Win32 method `GetLastError` is converted to a value of type `HRESULT` and can be retrieved using the `get_error_code` method.  \n  \n## Inheritance Hierarchy  \n `exception`  \n  \n `scheduler_resource_allocation_error`  \n  \n## Requirements  \n **Header:** concrt.h  \n  \n **Namespace:** concurrency  \n  \n##  <a name=\"get_error_code\"></a>  scheduler_resource_allocation_error::get_error_code Method  \n Returns the error code that caused the exception.  \n  \n```\nHRESULT get_error_code() const throw();\n```  \n  \n### Return Value  \n The `HRESULT` value of the error that caused the exception.  \n  \n##  <a name=\"ctor\"></a>  scheduler_resource_allocation_error::scheduler_resource_allocation_error Constructor  \n Constructs a `scheduler_resource_allocation_error` object.  \n  \n```\nscheduler_resource_allocation_error(\n    _In_z_ const char* _Message,\n    HRESULT _Hresult) throw();\n\nexplicit _CRTIMP scheduler_resource_allocation_error(\n    HRESULT _Hresult) throw();\n```  \n  \n### Parameters  \n `_Message`  \n A descriptive message of the error.  \n  \n `_Hresult`  \n The `HRESULT` value of the error that caused the exception.  \n  \n## See Also  \n [concurrency Namespace](concurrency-namespace.md)\n"}