{"nodes":[{"pos":[12,66],"content":"scheduler_worker_creation_error Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"scheduler_worker_creation_error Class | Microsoft Docs","pos":[0,54]}]},{"pos":[684,721],"content":"scheduler_worker_creation_error Class","linkify":"scheduler_worker_creation_error Class","nodes":[{"content":"scheduler_worker_creation_error Class","pos":[0,37]}]},{"content":"This class describes an exception thrown because of a failure to create a worker execution context in the Concurrency Runtime.","pos":[722,848]},{"pos":[857,863],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[969,976],"content":"Members","linkify":"Members","nodes":[{"content":"Members","pos":[0,7]}]},{"pos":[986,1005],"content":"Public Constructors","linkify":"Public Constructors","nodes":[{"content":"Public Constructors","pos":[0,19]}]},{"content":"Name","pos":[1012,1016]},{"content":"Description","pos":[1017,1028]},{"pos":[1066,1151],"content":"<bpt id=\"p1\">[</bpt>scheduler_worker_creation_error::scheduler_worker_creation_error Constructor<ept id=\"p1\">](#ctor)</ept>","source":"[scheduler_worker_creation_error::scheduler_worker_creation_error Constructor](#ctor)"},{"content":"Overloaded.","pos":[1152,1163]},{"content":"Constructs a <ph id=\"ph1\">`scheduler_worker_creation_error`</ph> object.","pos":[1164,1218],"source":" Constructs a `scheduler_worker_creation_error` object."},{"pos":[1228,1235],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This exception is typically thrown when a call to the operating system to create execution contexts from within the Concurrency Runtime fails.","pos":[1239,1381]},{"content":"Execution contexts are threads that execute tasks in the Concurrency Runtime.","pos":[1382,1459]},{"content":"The error code which would normally be returned from a call to the Win32 method <ph id=\"ph1\">`GetLastError`</ph> is converted to a value of type <ph id=\"ph2\">`HRESULT`</ph> and can be retrieved using the base class method <ph id=\"ph3\">`get_error_code`</ph>.","pos":[1460,1663],"source":" The error code which would normally be returned from a call to the Win32 method `GetLastError` is converted to a value of type `HRESULT` and can be retrieved using the base class method `get_error_code`."},{"pos":[1672,1693],"content":"Inheritance Hierarchy","linkify":"Inheritance Hierarchy","nodes":[{"content":"Inheritance Hierarchy","pos":[0,21]}]},{"pos":[1715,1798],"content":"<bpt id=\"p1\">[</bpt>scheduler_resource_allocation_error<ept id=\"p1\">](scheduler-resource-allocation-error-class.md)</ept>","source":"[scheduler_resource_allocation_error](scheduler-resource-allocation-error-class.md)"},{"pos":[1847,1859],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1863,1883],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> concrt.h","source":"**Header:** concrt.h"},{"pos":[1890,1916],"content":"<bpt id=\"p1\">**</bpt>Namespace:<ept id=\"p1\">**</ept> concurrency","source":"**Namespace:** concurrency"},{"pos":[1926,2023],"content":"<bpt id=\"p1\">&lt;a name=\"ctor\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  scheduler_worker_creation_error::scheduler_worker_creation_error Constructor","linkify":"<a name=\"ctor\"></a>  scheduler_worker_creation_error::scheduler_worker_creation_error Constructor","source":"<a name=\"ctor\"></a>  scheduler_worker_creation_error::scheduler_worker_creation_error Constructor"},{"pos":[2027,2081],"content":"Constructs a <ph id=\"ph1\">`scheduler_worker_creation_error`</ph> object.","source":"Constructs a `scheduler_worker_creation_error` object."},{"pos":[2283,2293],"content":"Parameters","linkify":"Parameters","nodes":[{"content":"Parameters","pos":[0,10]}]},{"content":"A descriptive message of the error.","pos":[2311,2346]},{"content":"The <ph id=\"ph1\">`HRESULT`</ph> value of the error that caused the exception.","pos":[2367,2426],"source":" The `HRESULT` value of the error that caused the exception."},{"pos":[2435,2443],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"pos":[2447,2496],"content":"<bpt id=\"p1\">[</bpt>concurrency Namespace<ept id=\"p1\">](concurrency-namespace.md)</ept>","source":"[concurrency Namespace](concurrency-namespace.md)"}],"content":"---\ntitle: \"scheduler_worker_creation_error Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nf1_keywords: \n  - \"concrt/concurrency::scheduler_worker_creation_error\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"scheduler_worker_creation_error class\"\nms.assetid: 4aec1c3e-c32a-41b2-899d-2d898f23b3c7\ncaps.latest.revision: 9\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# scheduler_worker_creation_error Class\nThis class describes an exception thrown because of a failure to create a worker execution context in the Concurrency Runtime.  \n  \n## Syntax  \n  \n```\nclass scheduler_worker_creation_error : public scheduler_resource_allocation_error;\n```  \n  \n## Members  \n  \n### Public Constructors  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[scheduler_worker_creation_error::scheduler_worker_creation_error Constructor](#ctor)|Overloaded. Constructs a `scheduler_worker_creation_error` object.|  \n  \n## Remarks  \n This exception is typically thrown when a call to the operating system to create execution contexts from within the Concurrency Runtime fails. Execution contexts are threads that execute tasks in the Concurrency Runtime. The error code which would normally be returned from a call to the Win32 method `GetLastError` is converted to a value of type `HRESULT` and can be retrieved using the base class method `get_error_code`.  \n  \n## Inheritance Hierarchy  \n `exception`  \n  \n [scheduler_resource_allocation_error](scheduler-resource-allocation-error-class.md)  \n  \n `scheduler_worker_creation_error`  \n  \n## Requirements  \n **Header:** concrt.h  \n  \n **Namespace:** concurrency  \n  \n##  <a name=\"ctor\"></a>  scheduler_worker_creation_error::scheduler_worker_creation_error Constructor  \n Constructs a `scheduler_worker_creation_error` object.  \n  \n```\nscheduler_worker_creation_error(\n    _In_z_ const char* _Message,\n    HRESULT _Hresult) throw();\n\nexplicit _CRTIMP scheduler_worker_creation_error(\n    HRESULT _Hresult) throw();\n```  \n  \n### Parameters  \n `_Message`  \n A descriptive message of the error.  \n  \n `_Hresult`  \n The `HRESULT` value of the error that caused the exception.  \n  \n## See Also  \n [concurrency Namespace](concurrency-namespace.md)\n"}