{"nodes":[{"pos":[12,69],"content":"Exceptions: Examining Exception Contents | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Exceptions: Examining Exception Contents | Microsoft Docs","pos":[0,57]}]},{"content":"Exceptions: Examining Exception Contents","pos":[848,888]},{"content":"Although a <bpt id=\"p1\">**</bpt>catch<ept id=\"p1\">**</ept> block's argument can be of almost any data type, the MFC functions throw exceptions of types derived from the class <ph id=\"ph1\">`CException`</ph>.","pos":[889,1039],"source":"Although a **catch** block's argument can be of almost any data type, the MFC functions throw exceptions of types derived from the class `CException`."},{"content":"To catch an exception thrown by an MFC function, then, you write a <bpt id=\"p1\">**</bpt>catch<ept id=\"p1\">**</ept> block whose argument is a pointer to a <ph id=\"ph1\">`CException`</ph> object (or an object derived from <ph id=\"ph2\">`CException`</ph>, such as <ph id=\"ph3\">`CMemoryException`</ph>).","pos":[1040,1245],"source":" To catch an exception thrown by an MFC function, then, you write a **catch** block whose argument is a pointer to a `CException` object (or an object derived from `CException`, such as `CMemoryException`)."},{"content":"Depending on the exact type of the exception, you can examine the data members of the exception object to gather information about the specific cause of the exception.","pos":[1246,1413]},{"content":"For example, the <ph id=\"ph1\">`CFileException`</ph> type has the <ph id=\"ph2\">`m_cause`</ph> data member, which contains an enumerated type that specifies the cause of the file exception.","pos":[1420,1571],"source":"For example, the `CFileException` type has the `m_cause` data member, which contains an enumerated type that specifies the cause of the file exception."},{"content":"Some examples of the possible return values are <bpt id=\"p1\">**</bpt>CFileException::fileNotFound<ept id=\"p1\">**</ept> and <bpt id=\"p2\">**</bpt>CFileException::readOnly<ept id=\"p2\">**</ept>.","pos":[1572,1686],"source":" Some examples of the possible return values are **CFileException::fileNotFound** and **CFileException::readOnly**."},{"content":"The following example shows how to examine the contents of a <ph id=\"ph1\">`CFileException`</ph>.","pos":[1693,1771],"source":"The following example shows how to examine the contents of a `CFileException`."},{"content":"Other exception types can be examined similarly.","pos":[1772,1820]},{"pos":[1838,1858],"content":"NVC_MFCExceptions#13"},{"pos":[1937,2165],"content":"For more information, see <bpt id=\"p1\">[</bpt>Exceptions: Freeing Objects in Exceptions<ept id=\"p1\">](../mfc/exceptions-freeing-objects-in-exceptions.md)</ept> and <bpt id=\"p2\">[</bpt>Exceptions: Catching and Deleting Exceptions<ept id=\"p2\">](../mfc/exceptions-catching-and-deleting-exceptions.md)</ept>.","source":"For more information, see [Exceptions: Freeing Objects in Exceptions](../mfc/exceptions-freeing-objects-in-exceptions.md) and [Exceptions: Catching and Deleting Exceptions](../mfc/exceptions-catching-and-deleting-exceptions.md)."},{"content":"See Also","pos":[2174,2182]},{"content":"Exception Handling","pos":[2187,2205]}],"content":"---\ntitle: \"Exceptions: Examining Exception Contents | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"exception handling, MFC\"\n  - \"try-catch exception handling, MFC function exceptions\"\n  - \"catch blocks, MFC function exceptions\"\n  - \"CException class, class exceptions\"\n  - \"try-catch exception handling, exception contents\"\n  - \"throwing exceptions, exception contents\"\nms.assetid: dfda4782-b969-4f60-b867-cc204ea7f33a\ncaps.latest.revision: 10\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Exceptions: Examining Exception Contents\nAlthough a **catch** block's argument can be of almost any data type, the MFC functions throw exceptions of types derived from the class `CException`. To catch an exception thrown by an MFC function, then, you write a **catch** block whose argument is a pointer to a `CException` object (or an object derived from `CException`, such as `CMemoryException`). Depending on the exact type of the exception, you can examine the data members of the exception object to gather information about the specific cause of the exception.  \n  \n For example, the `CFileException` type has the `m_cause` data member, which contains an enumerated type that specifies the cause of the file exception. Some examples of the possible return values are **CFileException::fileNotFound** and **CFileException::readOnly**.  \n  \n The following example shows how to examine the contents of a `CFileException`. Other exception types can be examined similarly.  \n  \n [!code-cpp[NVC_MFCExceptions#13](../mfc/codesnippet/cpp/exceptions-examining-exception-contents_1.cpp)]  \n  \n For more information, see [Exceptions: Freeing Objects in Exceptions](../mfc/exceptions-freeing-objects-in-exceptions.md) and [Exceptions: Catching and Deleting Exceptions](../mfc/exceptions-catching-and-deleting-exceptions.md).  \n  \n## See Also  \n [Exception Handling](../mfc/exception-handling-in-mfc.md)\n\n"}